### PR TITLE
dokumentnummer is not allowed as part of incominf payload. nikita will

### PR DESCRIPTION
**Pull request by tsodring**
throw a 400 in a while. Currently runtest should not upload dokumentnummer

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
What changed in runtest line 1232?

Also, import-uttrekk need to change to exclude this field.

**Comment by tsodring** [comment]
1232 was an empty line I believe. I think the other examples did not have this empty line

**Comment by petterreinholdtsen** [comment]
1232 is the 'tittel' line.

**Comment by tsodring** [comment]
From what I can tell the following occured:

                - 'tittel'          : u'Title of screened test document description created %s' % now,
                - 'dokumentnummer' : 3,
                + 'tittel'          : u'Title of screened test document description created %s' % now,          

When _'dokumentnummer' : 3_ line came out, the tittel line moved. You know git and diff better than I do, but the information is still there.

**Comment by petterreinholdtsen** [comment]
I squashed the commits, got rid of the unwanted trailing white space change and commited the change as 77741c71b1d5c26f809c38b05d8ac727768861a0

**Pull request closed without merging**
